"""
electricSphere uses information generated by the user to 
calculate the electric field at a point in space produced 
by a sphere with constant charge density placed at another
point in space.
"""
import numpy as np

v=lambda r:4/3*np.pi*r**3
"""v is the volume of the sphere"""

a=lambda r: r**2*np.pi*4
"""a is the surface area of a sphere with radius defined by r"""

sv=lambda p,o: p-o
"""sv is the separation vector between p and o"""

qe=lambda cd,r: v(r)*cd
"""qe is the charge enclosed by the sphere"""

def get_vmag(v1):
    """getVMag returns the magnitude of a 3D vector"""
    return np.sqrt(v1[0]**2+v1[1]**2+v1[2]**2)

def get_uvec(v1,m):
    """getUVec returns the unit vector of vector v. m is the magnitude of that vector"""
    if m==0:
        return [0,0,0]
    return v1/m

def inside(r,v1):
    """inside determines whether or not the vector v has 
    greater magnitude r and returns either the magnitude of v or r
    """
    if r>=get_vmag(v1):
        return get_vmag(v1)
    return r

def get_field_mag(cd,r,m):
    """getFieldMag returns the magnitude of the electric field"""
    eps=8.85*10**-12
    return qe(cd,r)/(eps*a(m))

def zero_condition(v1):
    """zeroCondition returns a list with a number of elements 
    defined by whether or not the elements of v are zero.
    This way, the number of zero elements in the 
    separation vector may be known.
    """
    return [1 for i in v1 if i==0]

def elec_field(o,cd,r,p):
    """elecField returns a vector which defines the 
    electric field of a sphere which has its center 
    located at point o, a charge density cd, and a 
    radius r at point p.
    """

    m=get_vmag(sv(p,o)) #m is the magnitude of the separation vector between p and o
    r=inside(r,sv(p,o))
    #if point p is inside the sphere, the radius is
    # reduced to the magnitude of the separation vector

    if len(zero_condition(sv(p,o)))==3:
    #if the separation vector is zero, a 3-dimensional zero vector is returned.

        return np.array([0,0,0])

    return get_field_mag(cd,r,m)*get_uvec(sv(p,o),m)

def get_field(o,cd,r,p):
    """getField just prints out the result of elecField in an easily readable way."""
    e=elec_field(o,cd,r,p)
    return (
        "The electric Field is defined by the vector\
 ["+str(e[0])+"x,", str(e[1])+"y,",str(e[2])+"z] V/m"
    )

if __name__=="__main__":
    print(get_field(np.array([0,0,0]), 1, .5, np.array([.8,.9,.3])))
